version: "3"
#声明一个网络名称,最终网络名称= 项目名称_networks  =>  web_networks ; docker network ls查看
networks:
  networks:
services:
  php7apache24node16:
    image: run/php7apache24node16:v1
    build:
       context: ../../../docker-file/run/php7apache24node16
       dockerfile: Dockerfile
    volumes:
      - /Users/fooldoc/web:/web
      - /Users/fooldoc/weblog:/weblog
      - /Users/fooldoc/web/webconfig/apache/docker/vhost:/usr/local/apache/conf/vhost
      - /tmp:/tmp
    environment:
         #ifconfig docker0的ip自己修改
      - HOST_IP=docker.for.mac.host.internal
      #host文件路径
      - HOST_PATH=/work/webconfig/host/4399/hosts
    #使用某个网络
    networks:
    - networks
  nginx:
    image: run/nginx1.8:v1
    build:
       context: ../../../docker-file/run/nginx1.8
       dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /Users/fooldoc/web:/web
      - /Users/fooldoc/weblog:/weblog
      - /Users/fooldoc/web/webconfig/nginx/docker/vhost:/usr/local/nginx/conf/vhost
      - /tmp:/tmp
    links:
      - php7apache24node16:php7
    #使用某个网络
    networks:
    - networks
  mysql8.0:
    image: run/mysql8.0:v1
    build:
       context: ../../../docker-file/run/mysql8.0
       dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
    #ifconfig docker0的ip自己修改
      - HOST_IP=docker.for.mac.host.internal
    #使用某个网络
    networks:
    - networks