version: "3"
#声明一个网络名称,最终网络名称= 项目名称_networks  =>  web_networks ; docker network ls查看
networks:
  networks:
services:
  php54apache24:
    image: run/php54apache24:v1
    build:
      context: ../../../docker-file/run/php54apache24
      dockerfile: Dockerfile
    environment:
    #ifconfig docker0的ip自己修改
    - HOST_IP=docker.for.mac.host.internal
    #host文件路径
#    - HOST_PATH=/etc/hosts
    volumes:
      - /tmp:/tmp
    external_links:
    - kafka:kafka
    #使用某个网络
    networks:
      - networks
  nginx:
    image: run/nginx1.8:v1
    build:
      context: ../../../docker-file/run/nginx1.8
      dockerfile: Dockerfile
    ports:
    - "80:80"
    volumes:
    - /tmp:/tmp
    links:
    - php54apache24:php54
    networks:
      - networks
  mysql8.0:
      image: run/mysql8.0:v1
      build:
        context: ../../../docker-file/run/mysql8.0
        dockerfile: Dockerfile
      ports:
      - "3306:3306"
      environment:
      #ifconfig docker0的ip自己修改
      - HOST_IP=docker.for.mac.host.internal
      networks:
        - networks