version: "3"
services:
  memcached1.5.22:
    image: memcached:1.5.22-alpine
    ports:
    - "11211:11211"
#使用web服务这个网络,这样就可以互通了
networks:
      default:
        external:
          name: web_networks