version: "3"
services:
  #  https://hub.docker.com/layers/elasticsearch/library/elasticsearch/5.5.2-alpine/images/sha256-e5a0a6044f71be0fa35f2964f926ae17d915a156b7e6ff4263a5fd31e9f164fb
  go:
    image: go:1.12
    build:
      context: ../../../docker-file/run/go
      dockerfile: Dockerfile
    environment:
    #ifconfig docker0的ip自己修改
    - HOST_IP=docker.for.mac.host.internal
    volumes:
    - /tmp:/tmp
    - /www:/www
    - /web:/web
    external_links:
    - kafka:kafka
networks:
  default:
    external:
      name: web_networks